# Generated by Django 3.2 on 2021-06-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='universe',
            new_name='university',
        ),
    ]
